### PR TITLE
Fix UB with non_exhaustive enums

### LINKED ISSUE #9: Fix UB with `int` to `enum` conversion
`non_exhaustive` attribute doesn't tell the compiler that some variants might exist which aren't specified as I assumed while writing the code.

Any code like [this](
https://github.com/Enter-tainer/zint-wasi/blob/832f61fc21ca2d6477fa1c5efce1d8f0b0ae6e73/zint-wasm-rs/src/error.rs#L25C1-L32C2) is UB:
```rust
impl ZintWarning {
    const LAST: u32 = ZINT_WARN_NONCOMPLIANT;

    /// This function isn't unsafe because `ZintWarning` is `non_exhaustive`.
    pub fn from_code(code: u32) -> Self {
        unsafe { std::mem::transmute(code) }
    }
}
```

UB is unlikely to be triggered by an external crate using `ZintWarning` because they're forced to match on `_`, but it'd be UB for `zint-wasm-rs` to match on those values.

`from_code` should be turned into a match statement and `ZintWarning::Other(u32)` should be added.

Affected types & fixes:
- [`ZintWarning`](https://github.com/Enter-tainer/zint-wasi/blob/832f61fc21ca2d6477fa1c5efce1d8f0b0ae6e73/zint-wasm-rs/src/error.rs#L10); cause [`ZintWarning::from_code`](https://github.com/Enter-tainer/zint-wasi/blob/832f61fc21ca2d6477fa1c5efce1d8f0b0ae6e73/zint-wasm-rs/src/error.rs#L29)
  - [ ] Add `ZintWarning::Other(u32)` variant
- [`QRMatrixOption`](https://github.com/Enter-tainer/zint-wasi/blob/832f61fc21ca2d6477fa1c5efce1d8f0b0ae6e73/zint-wasm-rs/src/options/option3.rs#L45); cause: [`<QRMatrixOption as TryFrom<u32>>::try_from`](https://github.com/Enter-tainer/zint-wasi/blob/832f61fc21ca2d6477fa1c5efce1d8f0b0ae6e73/zint-wasm-rs/src/options/option3.rs#L53)
  - [ ] Turn `QRMatrixOption` into a `u32` wrapper struct.
- [~~`Symbology`~~](https://github.com/Enter-tainer/zint-wasi/blob/832f61fc21ca2d6477fa1c5efce1d8f0b0ae6e73/zint-wasm-rs/src/options/symbology.rs#L9) is fine because we don't construct invalid variants.

### PR DESCRIPTION
**Pull request by Caellian**
Closes #9.

I also added `QRMask` enum for future use. I imagine users specifying `mask: 5` option instead of `option_3: (5 + 1) << 8`, but I'll do that in a separate PR.
Included cleaned up graphics from Wiki in assets for that purpose as well.

### CODE REVIEW

File: zint-wasm-rs/src/options/option3.rs [hunk 1]
```diff
@@ -37,35 +37,106 @@ impl TryFrom<u32> for DataMatrixOption {
...
-            }
-        })
+        let mask = QRMatrixOption::from_bits_truncate(value);
+        match mask {
+            invalid if invalid.bits() != value => Err(Error::UnknownOption {
+                which: "option_3",
+                value: Box::new(value),
+            }),
+            valid => Ok(valid)
+        }
```
Comment (Caellian) [inline zint-wasm-rs/src/options/option3.rs:139]: This cleans up changes from #5. Now it will be easier to extend in future.
